
auth.token=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

defaults.org=buenos-panes
defaults.project=react-native

defaults.url=https://sentry.io/
